name: vegeta
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7
  - mafft=7.470
  - locarna=2.0.0RC8
  - glpk=4.65
  - numpy=1.18.5
  - colorlog=4.1.0
  - biopython=1.76
  - docopt=0.6.2
  - scipy=1.4.1